### ISSUE TITLE
command line version

### ISSUE THREAD

**Issue by cieplutki** [JosePineiro/LittleZip#2]
Hey, 
I have checked your program and it works fabulous. It's great but there is a problem - it's too user friendly - it can't be utilised in script nor combined with file manager as "plugin archiver" as it doesn't process command line. Have you got or possibly can do command line version?

PS. Tried to put it in request's but couldn't.

**Comment by JosePineiro** [comment]
Please, Test using this parameters:
Littlezip "Source directory" "file.zip"

**Comment by cieplutki** [comment]
Just tested file bin/Release/LittleZipTest.exe  and it is failing with unhandled exception: (no matter whether paths are relative or absolute)

```
************** Exception Text **************
System.Exception: Invalid ZIP file
In LittleZip.Create
   at System.IO.Compression.LittleZip..ctor(String pathFilename, String zipComment)
   at LittleZipTest.LittleZipTest.buttonZIP_Click(Object sender, EventArgs e)
   at LittleZipTest.LittleZipTest.LittleZipTest_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
```

When I run it from cygwin bash it just crashes, without any message.

--

IMO the parameters should be opposite like in all other archivers: 
$ pak \<file.pak\> \<list of files to pak\>

**Comment by JosePineiro** [comment]
Please. Test the new version.

**Comment by cieplutki** [comment]
Works very well.
Will still insist to swap arguments so the archive.zip would be first as in all other packers. It will not change functionality whatsoever rather improve.

**Comment by JosePineiro** [comment]
Swapped arguments. Please, suggest command for set the compression level. To be one number betwen 0 and 500.

**Comment by cieplutki** [comment]
What would you need 500 levels for? Like in standard zip/gzip -1 to -9 and here up to -12. Just like you use in your api and as it is in libdeflate. Believe or not, but when I see compressor with hundreds of compression levels it puts me off.
I use -12 by default unless I really want to make it quick (which is rare). But that's less of concern if you use it as packer (like here). Most of the time you don't bother that much of compression time in desktop environment and if you do then you have time to adjust compression for your needs anyway.

**Comment by JosePineiro** [comment]
The level are for the compression algorithm select
0-9 standard ZIP
10-12 libdeflate 'lazy' algorithm
13 -500 zopfly algorithm. A more level, more compresion and slowwwwww...
What command line parameters do you need?
